<a href="https://colab.research.google.com/github/Deepikapanchakarla/FML/blob/main/decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [ ]:
iris=datasets.load_iris()
x=iris.data
y=iris.target

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=35)

In [10]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)


In [11]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [12]:
x_test=scaler.transform(x_test)

In [13]:
y_pred=model.predict(x_test)

In [16]:
model.score(x_train,y_train)

1.0

In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [15]:
model.score(x_test,y_test)

1.0

In [18]:
print(confusion_matrix(y_test,y_pred))

[[11  0  0]
 [ 0 10  0]
 [ 0  0  9]]
